### ISSUE TITLE
Congratulations and question

### ISSUE THREAD

**Issue by frederikhors** [schneidersteve/buckpal-rust#1]
Congratulations for your project.

Can I ask you how to deal with db transactions calls?

**Comment by schneidersteve** [comment]
It should be handled in the service. If you were using the Java Spring Framework for example you would just annotate your service method with ```@Transaction``` and the Framework would handle the transaction. Another solution in the Java world would be aspect-orientated programming.

But this is Rust and i didnt searched for a solution yet.
